### ISSUE TITLE
Preserves boxes in use?

### ISSUE THREAD

**Issue by wizonesolutions** [swisnl/vagrant-remove-old-box-versions#3]
I know that some of the newer Vagrant versions used linked clones, meaning if I remove a base box that is being used by a VM, I'll lose all those VMs as well. Does this plugin protect against that? I'm not sure to what degree Vagrant itself remembers which boxes are being used by what VMs.

**Comment by bbrala** [comment]
Vagrant keeps track of boxes that are used. The plugin uses the normal delete method of vagrant, which gives it the same protection as the normal vagrant command does.
