### ISSUE TITLE
Support removing obsolete linked clones

### ISSUE THREAD

**Issue by J0WI** [swisnl/vagrant-remove-old-box-versions#4]
Vagrant 1.8 allows you to use [linked clones](https://www.vagrantup.com/docs/virtualbox/configuration.html#linked-clones).
Removing an outdated box does not remove the master (base) image from VirtualBox so far. Would be great if this can be done by this plugin.

**Comment by bbrala** [comment]
This plugin aims to remove everything outdated. I think it should remove old versions of masters if they are updated. It is not a plugin to remove unused boxes. So i feel this really is outside the scope, sorry.

**Comment by J0WI** [comment]
> I think it should remove old versions of masters if they are updated.

@bbrala This is exactly what I meant, so I'm asking you to reconsider this feature request.

**Comment by bbrala** [comment]
It doesnt do that? If that is true, i indeed feel it should.

**Comment by bbrala** [comment]
Since this plugin is now core vagrant, please reopen this issue there if it persists.

Regards, Bjorn
